/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QuanLyBanVeMayBay.GUI.form;

import QuanLyBanVeMayBay.BUS.CTHoaDonBUS;
import QuanLyBanVeMayBay.BUS.HoaDonBUS;
import QuanLyBanVeMayBay.BUS.NhanVienBUS;
import QuanLyBanVeMayBay.DTO.CTHoaDon;
import QuanLyBanVeMayBay.DTO.HoaDon;
import QuanLyBanVeMayBay.DTO.NhanVien;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DELL
 */
public class HoaDonGUI extends javax.swing.JPanel {
  DecimalFormat dcf = new DecimalFormat("###,###");
    DefaultTableModel dtmCTHoaDon = new DefaultTableModel();
    DefaultTableModel dtmHoaDon = new DefaultTableModel();
    HoaDonBUS hoadonBUS = new HoaDonBUS();
    ArrayList<HoaDon> dshd = new ArrayList<HoaDon>();
    CTHoaDonBUS CTHoaDonBUS = new CTHoaDonBUS();
    /**
     * Creates new form HoaDonGUII
     */
    public HoaDonGUI() {
        initComponents();
        loadDataListHoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMaHDCT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMaLoaiVe = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSoLuongCT = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtThue = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtThanhTienCT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTHoaDon = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Chi tiết hóa đơn");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 22, 470, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Thông tin hóa đơn");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 26, 330, 50));

        jLabel3.setText("Mã hóa đơn");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });
        add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 92, 252, -1));

        jLabel4.setText("Mã khách hàng");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 132, 252, -1));

        jLabel5.setText("Mã nhân viên");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 172, 252, -1));

        jLabel6.setText("Mã khuyến mãi");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        add(txtMaKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 212, 252, -1));

        jLabel7.setText("Ngày lập");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtNgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayLapActionPerformed(evt);
            }
        });
        add(txtNgayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 246, 252, -1));

        jLabel8.setText("Tổng tiền");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 286, 252, -1));

        jLabel9.setText("Giá từ :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 335, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 332, 80, -1));

        jLabel10.setText("đến");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 335, -1, -1));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 332, 80, -1));

        jLabel11.setText("Ngày lập từ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 375, -1, -1));
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 372, 80, -1));

        jLabel12.setText("đến");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 375, -1, -1));
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 372, 80, -1));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã khách hàng", "Mã nhân viên", "Mã khuyến mãi", "Ngày lập", "Tổng tiền"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 412, 530, -1));
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 605, -1, -1));

        jLabel13.setText("Mã hóa đơn");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, -1));

        txtMaHDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDCTActionPerformed(evt);
            }
        });
        add(txtMaHDCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 450, -1));

        jLabel14.setText("Mã loại vé");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));
        add(txtMaLoaiVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 450, -1));

        jLabel16.setText("Số Lượng");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));
        add(txtSoLuongCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 450, -1));

        jLabel18.setText("Thuế");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, -1, -1));

        txtThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThueActionPerformed(evt);
            }
        });
        add(txtThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 450, -1));

        jLabel19.setText("Thành tiền");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));
        add(txtThanhTienCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 450, -1));

        tblCTHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã loại vé", "Số lượng", "Thuế", "Thành tiền"
            }
        ));
        tblCTHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCTHoaDon);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 730, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayLapActionPerformed

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void txtThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThueActionPerformed

    private void txtMaHDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDCTActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        xuLyHienHoaDon();
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void tblCTHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTHoaDonMouseClicked
        // TODO add your handling code here:
        xuLyClickTblCTHoaDon();
    }//GEN-LAST:event_tblCTHoaDonMouseClicked
                   private void loadDataListHoaDon() {
		        
                            dtmHoaDon.setRowCount(0);
                            dshd = hoadonBUS.showListHoaDon();
                            Vector<Object> header = new Vector<Object>();
                            header.add("Mã hóa đơn");
                            header.add("Mã khách hàng");
                            header.add("Mã nhân viên");
                            header.add("Mã khuyến mãi");
                            header.add("Ngày lập");
                            header.add("Tổng tiền");
                                                      
                                if (dtmHoaDon.getRowCount() == 0) {
                                    dtmHoaDon = new DefaultTableModel(header, 0);
                                }
                            for (HoaDon hd : dshd) {
                                Vector<Object> vec = new Vector<Object>();
                                vec.add(hd.getMaHD());
                                vec.add(hd.getMaKHThanhToan());
                                vec.add(hd.getMaNV());
                                vec.add(hd.getmaKM());
                                vec.add(hd.getNgayLap());
                                vec.add(hd.getTongTien());
                              

                                dtmHoaDon.addRow(vec);
                            }
                            tblHoaDon.setModel(dtmHoaDon);
                        }
		
		   

	
			private void xuLyHienHoaDon() {
				
			        int row = tblHoaDon.getSelectedRow();
			        if (row > -1) {
			            String maHD = tblHoaDon.getValueAt(row, 0) + "";
			            String maKH = tblHoaDon.getValueAt(row, 1) + "";
			            String maNV = tblHoaDon.getValueAt(row, 2) + "";
			            String maKM = tblHoaDon.getValueAt(row, 3) + "";
			            String ngayLap = tblHoaDon.getValueAt(row, 4) + "";
                                    String tongTien = tblHoaDon.getValueAt(row, 5) + "";

			            txtMaHD.setText(maHD);
			            txtMaKH.setText(maKH);
			            txtMaNV.setText(maNV);
			            txtMaKM.setText(maKM);
			            txtNgayLap.setText(ngayLap);
                                    txtTongTien.setText(tongTien);
                                    loadDataTblCTHoaDon(maHD);
			        }
                                
                               
	
			}
			

			private void loadDataTblCTHoaDon() {
			CTHoaDonBUS.docListCTHoaDon();
		        ArrayList<CTHoaDon> listCTHoaDon = CTHoaDonBUS.getListCTHoaDon();
		        addDataTableCTHoaDon(listCTHoaDon);
		      }
                        
                        private void loadDataTblCTHoaDon(String maHD) {
                                CTHoaDonBUS.docListCTHoaDon();
			        ArrayList<CTHoaDon> listCTHoaDon = CTHoaDonBUS.getListCTHoaDonTheoMaHD(maHD);

			        addDataTableCTHoaDon(listCTHoaDon);
			  }
			
			 private void addDataTableCTHoaDon(ArrayList<CTHoaDon> listCTHoaDon) {
			        dtmCTHoaDon.setRowCount(0);
			        Vector<Object> header = new Vector<>();
			        header.add("Mã Hóa Đơn");
			        header.add("Mã Loại Vé");
			        header.add("Số Lượng");
			        header.add("Mã Khuyến Mãi");
			        header.add("Thuế");
			        header.add("Thành Tiền");
			        if (dtmCTHoaDon.getRowCount() == 0) {
			        	dtmCTHoaDon = new DefaultTableModel(header, 0);
				       }
			        for (CTHoaDon ct : listCTHoaDon) {
			            Vector<String> vec = new Vector<>();
			            vec.add(ct.getMaHD() + "");
			            vec.add(ct.getMaLoaiVe() + "");
			            vec.add(ct.getSoLuongVe() + "");
			            vec.add(ct.getSoLuongVe() + "");
			            vec.add(dcf.format(ct.getThue()));
			            vec.add(dcf.format(ct.getThanhTien()));
			            dtmCTHoaDon.addRow(vec);
			        }
			        
			        tblCTHoaDon.setModel(dtmCTHoaDon);
			    }   
		
			 
			 
			 
			 private void xuLyClickTblCTHoaDon() {
			        int row = tblCTHoaDon.getSelectedRow();
			        if (row > -1) {
			            String maHD = tblCTHoaDon.getValueAt(row, 0) + "";
			            String maLoaiVe = tblCTHoaDon.getValueAt(row, 1) + "";
			            String soLuong = tblCTHoaDon.getValueAt(row, 2) + "";
			            String thue = tblCTHoaDon.getValueAt(row, 3) + "";
			            String thanhTien = tblCTHoaDon.getValueAt(row, 4) + "";

			            txtMaHDCT.setText(maHD);
			            txtMaLoaiVe.setText(maLoaiVe);
			            txtSoLuongCT.setText(soLuong);
			            txtThue.setText(thue);
			            txtThanhTienCT.setText(thanhTien);
			        }
			    }

			
			
			 private void xuLyTimTheoKhoangNgay() {
//			        ArrayList<HoaDon> listHoaDon = CTHoaDonBUS.getListHoaDonTheoNgay(txtMinSearch.getText(), txtMaxSearch.getText());
//			        addDataListHoaDon(listHoaDon);
			    }

			    private void xuLyTimTheoKhoangGia() {
//			        ArrayList<HoaDon> listHoaDon = CTHoaDonBUS.getListHoaDonTheoGia(txtMinSearch.getText(), txtMaxSearch.getText());
//			        addDataListHoaDon(listHoaDon);
			    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tblCTHoaDon;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaHDCT;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtMaLoaiVe;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoLuongCT;
    private javax.swing.JTextField txtThanhTienCT;
    private javax.swing.JTextField txtThue;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
