/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QuanLyBanVeMayBay.GUI.form;

import QuanLyBanVeMayBay.BUS.NhanVienBUS;
import QuanLyBanVeMayBay.DTO.NhanVien;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class NhanVienGUI extends javax.swing.JPanel {
   DefaultTableModel dtmNhanVien = new DefaultTableModel();
    NhanVienBUS nhanvienBUS = new NhanVienBUS();
    ArrayList<NhanVien> dsnv = new ArrayList<NhanVien>();
    /**
     * Creates new form NhanVienGUII
     */
    public NhanVienGUI() {
        initComponents();
        loadDataTblNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Gioitinhnv = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtCanCuoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        Themnv = new javax.swing.JButton();
        Luunv = new javax.swing.JButton();
        Xoanv = new javax.swing.JButton();
        Timkiemnv = new javax.swing.JButton();
        NhapExcel = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_nv = new javax.swing.JTable();
        XuatExcel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTimNV = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();

        jLabel2.setText("Quản Lý Nhân Viên");

        jLabel3.setText("Mã nhân viên");

        jLabel4.setText("Họ nhân viên");

        jLabel5.setText("Tên nhân viên");

        jLabel6.setText("Giới tính nhân viên");

        Gioitinhnv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        Gioitinhnv.setToolTipText("");

        jLabel7.setText("Căn cước nhân viên");

        jLabel8.setText("Số điện thoại nhân viên");

        Themnv.setText("Thêm");
        Themnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemnvActionPerformed(evt);
            }
        });

        Luunv.setText("Lưu");
        Luunv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuunvActionPerformed(evt);
            }
        });

        Xoanv.setText("Xóa");
        Xoanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoanvActionPerformed(evt);
            }
        });

        Timkiemnv.setText("Tìm Kiếm");
        Timkiemnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimkiemnvActionPerformed(evt);
            }
        });

        NhapExcel.setText("Nhập Excel");

        jButton6.setText("jButton6");

        table_nv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ nhân viên", "Tên nhân viên", "Giới tính", "Căn cước", "Số điện thoại", "Lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_nvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_nv);

        XuatExcel.setText("Xuất Excel");
        XuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XuatExcelActionPerformed(evt);
            }
        });

        jLabel9.setText("Lương");

        jLabel10.setText("Tìm kiếm");

        txtMaNV.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Themnv)
                                        .addGap(48, 48, 48)
                                        .addComponent(Luunv)))
                                .addGap(54, 54, 54)
                                .addComponent(Xoanv)))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(1030, 1030, 1030))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLuong)
                                            .addComponent(txtTimNV))
                                        .addGap(741, 741, 741)))
                                .addComponent(jButton6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCanCuoc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Gioitinhnv, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Timkiemnv)
                                    .addGap(71, 71, 71)
                                    .addComponent(NhapExcel)
                                    .addGap(65, 65, 65)
                                    .addComponent(XuatExcel)))
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel9)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Gioitinhnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtCanCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Themnv)
                            .addComponent(Luunv)
                            .addComponent(Xoanv)
                            .addComponent(Timkiemnv)
                            .addComponent(NhapExcel)
                            .addComponent(XuatExcel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void XuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XuatExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XuatExcelActionPerformed

    private void ThemnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemnvActionPerformed
        // TODO add your handling code here:
        xuLyThemNhanVien();
    }//GEN-LAST:event_ThemnvActionPerformed

    private void table_nvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_nvMouseClicked
        // TODO add your handling code here:
        xuLyClickTblNhanVien();
    }//GEN-LAST:event_table_nvMouseClicked

    private void XoanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoanvActionPerformed
        // TODO add your handling code here:
        xuLyXoaNhanVien();
    }//GEN-LAST:event_XoanvActionPerformed

    private void LuunvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuunvActionPerformed
        // TODO add your handling code here:
        xuLySuaNhanVien();
    }//GEN-LAST:event_LuunvActionPerformed

    private void TimkiemnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimkiemnvActionPerformed
        // TODO add your handling code here:
        xuLyTimKiemNhanVien();
    }//GEN-LAST:event_TimkiemnvActionPerformed

    private void xuLyClickTblNhanVien() {
	        int row = table_nv.getSelectedRow();
	        if (row > -1) {
	        	txtMaNV.setText(table_nv.getValueAt(row, 0) + "");
	        	txtHo.setText(table_nv.getValueAt(row, 1) + "");
	        	txtTen.setText(table_nv.getValueAt(row, 2) + "");
	        	txtCanCuoc.setText(table_nv.getValueAt(row, 4) + "");
	        	txtSDT.setText(table_nv.getValueAt(row, 5) + "");
	        	txtLuong.setText(table_nv.getValueAt(row, 6) + "");

	            String gioiTinh = "";
	            if ((table_nv.getValueAt(row, 3) + "").equals("Nam")) {
	            	Gioitinhnv.setSelectedIndex(1);
	            } else {
	            	Gioitinhnv.setSelectedIndex(2);
	            }
	        }
	    }
	
	

	
	
	 private void xuLyThemNhanVien() {

	        String ho = txtHo.getText();
	        String ten = txtTen.getText();
	        String gioiTinh = Gioitinhnv.getSelectedItem() + "";
	        String cancuoc = txtCanCuoc.getText();
	        int sdt = Integer.parseInt(txtSDT.getText());
	        int luong = Integer.parseInt(txtLuong.getText());
	        nhanvienBUS.themNhanVien(ho, ten, gioiTinh, cancuoc , sdt , luong);
	       
	        showListNhanVien();
	        
	    }
	 
	 
	 private void xuLySuaNhanVien() {
//	        if (cmbGioiTinh.getSelectedIndex() == 0) {
//	            new MyDialog("HÃƒÂ£y chÃ¡Â»ï¿½n giÃ¡Â»â€ºi tÃƒÂ­nh!", MyDialog.ERROR_DIALOG);
//	            return;
//	        }
	        int ma = Integer.parseInt(txtMaNV.getText());
	        String ho = txtHo.getText();
	        String ten = txtTen.getText();
	        String gioiTinh = Gioitinhnv.getSelectedItem() + "";
	        String cancuoc = txtCanCuoc.getText();
	        int sdt = Integer.parseInt(txtSDT.getText());;
	        int luong = Integer.parseInt(txtLuong.getText());
	        nhanvienBUS.updateNhanVien(ma, ho, ten, gioiTinh, cancuoc , sdt , luong);
	        	
	            showListNhanVien();
	        
	    }
	 
	 
	  private void xuLyXoaNhanVien() {
		    String ma = txtMaNV.getText();
	        int i = table_nv.getSelectedRow();
	        int maNV = Integer.parseInt(ma);
	        
	        nhanvienBUS.xoaNhanVien(maNV);
	        dtmNhanVien.removeRow(i);
	        table_nv.setModel(dtmNhanVien);
	        txtMaNV.setText("");
	        txtHo.setText("");
	        txtTen.setText("");
	        txtLuong.setText("");
	        Gioitinhnv.setSelectedIndex(1);
	        txtCanCuoc.setText("");
	        txtSDT.setText("");
	        
    }
	  
	  
	  private void xuLyTimKiemNhanVien() {
	        dsnv = nhanvienBUS.timNhanVien(txtTimNV.getText());
	        dtmNhanVien.setRowCount(0);
	        for (QuanLyBanVeMayBay.DTO.NhanVien nv : dsnv) {
	            Vector<Object> vec = new Vector<>();
	            vec.add(nv.getMaNV());
	            vec.add(nv.getHoNV());
	            vec.add(nv.getTenNV());
	            vec.add(nv.getGioiTinh());
	            vec.add(nv.getNgaySinh());
	            vec.add(nv.getSdt());
	            vec.add(nv.getLuong());
	            dtmNhanVien.addRow(vec);
	        }
	        
	        table_nv.setModel(dtmNhanVien);
	    }
	  
	  
	  
	 

	 
	 
	 private void loadDataTblNhanVien() {
	        dtmNhanVien.setRowCount(0);
	        dsnv = nhanvienBUS.getDanhSachNhanVien();
	        Vector<Object> header = new Vector<Object>();
	        header.add("Mã Nhân Viên");
	        header.add("Họ Nhân Viên");
	        header.add("Tên Nhân Viên");
	        header.add("Giới Tính");
	        header.add("Căn Cước");
	        header.add("Số Điện Thoại");
		header.add("Lương");                            
		    if (dtmNhanVien.getRowCount() == 0) {
		    	dtmNhanVien = new DefaultTableModel(header, 0);
		    }
	        for (NhanVien nv : dsnv) {
                    Vector<Object> vec = new Vector<Object>();
	            vec.add(nv.getMaNV());
	            vec.add(nv.getHoNV());
	            vec.add(nv.getTenNV());
	            vec.add(nv.getGioiTinh());
	            vec.add(nv.getNgaySinh());
	            vec.add(nv.getSdt());
	            vec.add(nv.getLuong());

	            dtmNhanVien.addRow(vec);
	        }
	        table_nv.setModel(dtmNhanVien);
	    }
         
         public void showListNhanVien(){
                     dtmNhanVien.setRowCount(0);
	        dsnv = nhanvienBUS.showListNhanVien();
	        Vector<Object> header = new Vector<Object>();
	        header.add("Mã Nhân Viên");
	        header.add("Họ Nhân Viên");
	        header.add("Tên Nhân Viên");
	        header.add("Giới Tính");
	        header.add("Căn Cước");
	        header.add("Số Điện Thoại");
		header.add("Lương");                            
		    if (dtmNhanVien.getRowCount() == 0) {
		    	dtmNhanVien = new DefaultTableModel(header, 0);
		    }
	        for (NhanVien nv : dsnv) {
                    Vector<Object> vec = new Vector<Object>();
	            vec.add(nv.getMaNV());
	            vec.add(nv.getHoNV());
	            vec.add(nv.getTenNV());
	            vec.add(nv.getGioiTinh());
	            vec.add(nv.getNgaySinh());
	            vec.add(nv.getSdt());
	            vec.add(nv.getLuong());

	            dtmNhanVien.addRow(vec);
	        }
	        table_nv.setModel(dtmNhanVien);
         }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Gioitinhnv;
    private javax.swing.JButton Luunv;
    private javax.swing.JButton NhapExcel;
    private javax.swing.JButton Themnv;
    private javax.swing.JButton Timkiemnv;
    private javax.swing.JButton Xoanv;
    private javax.swing.JButton XuatExcel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_nv;
    private javax.swing.JTextField txtCanCuoc;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimNV;
    // End of variables declaration//GEN-END:variables
}
