/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QuanLyBanVeMayBay.GUI;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

import QuanLyBanVeMayBay.GUI.MayBayGUI;
import QuanLyBanVeMayBay.BUS.MayBayBUS;
import QuanLyBanVeMayBay.DTO.MayBayDTO;

/**
 *
 * @author Dell
 */
public class MayBayGUI extends javax.swing.JPanel {

    /**
     * Creates new form MayBayGUI
     */
    MayBayBUS maybayBUS = new MayBayBUS();
    DefaultTableModel dtmMayBay;
    ArrayList<MayBayDTO> dsmb = null;

    public MayBayGUI() {
        initComponents();
        getListMayBay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        txtMaMB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTenMB = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtMaHB = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtSoLuongGhe = new javax.swing.JTextField();
        jButtonThemMayBay = new javax.swing.JButton();
        jButtonSuaMayBay = new javax.swing.JButton();
        jButtonXoaMayBay = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMayBay = new javax.swing.JTable();
        txtTuKhoa = new javax.swing.JTextField();
        selectLuaChon = new javax.swing.JComboBox<>();
        seachMayBay = new javax.swing.JButton();

        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextPane1.setText("QUẢN LÝ MÁY BAY");
        jScrollPane1.setViewportView(jTextPane1);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Mã máy bay");

        txtMaMB.setText("jTextField1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tên máy bay");

        txtTenMB.setText("jTextField38");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setText("Mã hãng");

        txtMaHB.setText("jTextField39");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("Số lượng ghế");

        txtSoLuongGhe.setText("jTextField40");

        jButtonThemMayBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonThemMayBay.setText("Thêm");
        jButtonThemMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemMayBayActionPerformed(evt);
            }
        });

        jButtonSuaMayBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSuaMayBay.setText("Sửa");
        jButtonSuaMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaMayBayActionPerformed(evt);
            }
        });

        jButtonXoaMayBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonXoaMayBay.setText("Xóa");
        jButtonXoaMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaMayBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButtonThemMayBay)
                        .addGap(65, 65, 65)
                        .addComponent(jButtonSuaMayBay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jButtonXoaMayBay))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel40)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel39))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaMB)
                            .addComponent(txtTenMB)
                            .addComponent(txtMaHB)
                            .addComponent(txtSoLuongGhe))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(txtMaMB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtTenMB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel38)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtMaHB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel39)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtSoLuongGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonThemMayBay)
                            .addComponent(jButtonSuaMayBay)
                            .addComponent(jButtonXoaMayBay))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tableMayBay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã máy bay", "Tên máy bay", "Mã hãng", "Số lượng ghế"
            }
        ));
        tableMayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMayBayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableMayBay);

        txtTuKhoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTuKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuKhoaActionPerformed(evt);
            }
        });

        selectLuaChon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectLuaChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã máy bay", "Tên máy bay", "Mã hãng bay" }));

        seachMayBay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seachMayBay.setText("Tìm kiếm");
        seachMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seachMayBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(529, 529, 529))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(selectLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(seachMayBay)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seachMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemMayBayActionPerformed
        // TODO add your handling code here:
        themMayBay();
    }//GEN-LAST:event_jButtonThemMayBayActionPerformed

    private void jButtonSuaMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaMayBayActionPerformed
        // TODO add your handling code here:
        suaMayBay();
    }//GEN-LAST:event_jButtonSuaMayBayActionPerformed

    private void jButtonXoaMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaMayBayActionPerformed
        // TODO add your handling code here:
        xoaMayBay();
    }//GEN-LAST:event_jButtonXoaMayBayActionPerformed

    private void tableMayBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMayBayMouseClicked
        // TODO add your handling code here:
        clickTableRowMB();
    }//GEN-LAST:event_tableMayBayMouseClicked

    private void txtTuKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuKhoaActionPerformed

    private void seachMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seachMayBayActionPerformed
        // TODO add your handling code here:
        timKiemMayBay();
    }//GEN-LAST:event_seachMayBayActionPerformed

    public void themMayBay() {
        String tenMB = txtTenMB.getText();
        String maHB = txtMaHB.getText();
        int soLuongGhe = Integer.parseInt(txtSoLuongGhe.getText());
        MayBayDTO mb = new MayBayDTO();
        mb.setTenMayBay(tenMB);
        mb.setMaHang(maHB);
        mb.setSoLuongGhe(soLuongGhe);
        maybayBUS.themMayBay(mb);
    }

    public void suaMayBay() {
        String maMB = txtMaMB.getText();
        String tenMB = txtTenMB.getText();
        String maHB = txtMaHB.getText();
        int soLuongGhe = Integer.parseInt(txtSoLuongGhe.getText());
        MayBayDTO mb = new MayBayDTO(maMB, tenMB, maHB, soLuongGhe);

        maybayBUS.suaMayBay(mb);
    }

    public void xoaMayBay() {
        String maMB = txtMaMB.getText();

        maybayBUS.xoaMayBay(maMB);
    }

    public void getListMayBay() {
        dtmMayBay.setRowCount(0);
        dsmb = maybayBUS.getListMayBay();

        for (MayBayDTO mb : dsmb) {
            Vector vec = new Vector();
            vec.add(mb.getMaMayBay());
            vec.add(mb.getTenMayBay());
            vec.add(mb.getMaHang());
            vec.add(mb.getSoLuongGhe());

            dtmMayBay.addRow(vec);
        }
        tableMayBay.setModel(dtmMayBay);
    }

    public void clickTableRowMB() {
        int row = tableMayBay.getSelectedRow();
        if (row > -1) {
            txtMaMB.setText(tableMayBay.getValueAt(row, 0) + "");
            txtTenMB.setText(tableMayBay.getValueAt(row, 1) + "");
            txtMaHB.setText(tableMayBay.getValueAt(row, 2) + "");
            txtSoLuongGhe.setText(tableMayBay.getValueAt(row, 3) + "");
        }
    }

    public void timKiemMayBay() {
        String tuKhoa = txtTuKhoa.getText();
        String luaChon = selectLuaChon.getSelectedItem().toString();

        if (luaChon == "Mã máy bay") {
            dsmb = maybayBUS.timKiemMayBayTheoMa(tuKhoa);
        }

        if (luaChon == "Tên máy bay") {
            dsmb = maybayBUS.timKiemMayBayTheoTen(tuKhoa);
        }

        if (luaChon == "Mã hãng bay") {
            dsmb = maybayBUS.timKiemMayBayTheoHang(tuKhoa);
        }

        for (MayBayDTO mb : dsmb) {
            Vector vec = new Vector();
            vec.add(mb.getMaMayBay());
            vec.add(mb.getTenMayBay());
            vec.add(mb.getMaHang());
            vec.add(mb.getSoLuongGhe());

            dtmMayBay.addRow(vec);
        }
        tableMayBay.setModel(dtmMayBay);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSuaMayBay;
    private javax.swing.JButton jButtonThemMayBay;
    private javax.swing.JButton jButtonXoaMayBay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton seachMayBay;
    private javax.swing.JComboBox<String> selectLuaChon;
    private javax.swing.JTable tableMayBay;
    private javax.swing.JTextField txtMaHB;
    private javax.swing.JTextField txtMaMB;
    private javax.swing.JTextField txtSoLuongGhe;
    private javax.swing.JTextField txtTenMB;
    private javax.swing.JTextField txtTuKhoa;
    // End of variables declaration//GEN-END:variables
}
