/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QuanLyBanVeMayBay.GUI;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

import QuanLyBanVeMayBay.GUI.SanBayGUI;
import QuanLyBanVeMayBay.BUS.SanBayBUS;
import QuanLyBanVeMayBay.DTO.SanBayDTO;

/**
 *
 * @author Dell
 */
public class SanBayGUI extends javax.swing.JPanel {

    /**
     * Creates new form SanBayGUI
     */
    SanBayBUS sanbayBUS = new SanBayBUS();
    DefaultTableModel dtmSanBay;
    ArrayList<SanBayDTO> dssb = null;

    public SanBayGUI() {
        initComponents();
        getListSanBay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaSB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenSB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jButtonThemSanBay = new javax.swing.JButton();
        jButtonSuaSanBay = new javax.swing.JButton();
        jButtonXoaSanBay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSanBay = new javax.swing.JTable();
        txtTuKhoa = new javax.swing.JTextField();
        selectLuaChon = new javax.swing.JComboBox<>();
        searchSanBay = new javax.swing.JButton();

        jScrollPane1.setToolTipText("");
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextPane1.setText("QUẢN LÝ SÂN BAY");
        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã sân bay");

        txtMaSB.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên sân bay");

        txtTenSB.setText("jTextField2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Địa chỉ");

        txtDiaChi.setText("jTextField3");

        jButtonThemSanBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonThemSanBay.setText("Thêm");
        jButtonThemSanBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemSanBayActionPerformed(evt);
            }
        });

        jButtonSuaSanBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSuaSanBay.setText("Sửa");
        jButtonSuaSanBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaSanBayActionPerformed(evt);
            }
        });

        jButtonXoaSanBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonXoaSanBay.setText("Xóa");
        jButtonXoaSanBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaSanBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSB, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtTenSB)
                            .addComponent(txtDiaChi)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButtonThemSanBay)
                        .addGap(68, 68, 68)
                        .addComponent(jButtonSuaSanBay)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonXoaSanBay)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaSB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenSB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDiaChi)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThemSanBay)
                    .addComponent(jButtonSuaSanBay)
                    .addComponent(jButtonXoaSanBay))
                .addGap(42, 42, 42))
        );

        tableSanBay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sân bay", "Tên sân bay", "Địa chỉ"
            }
        ));
        tableSanBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSanBayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableSanBay);

        txtTuKhoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        selectLuaChon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectLuaChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã sân bay", "Tên sân bay", "Địa chỉ sân bay" }));

        searchSanBay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchSanBay.setText("Tìm kiếm");
        searchSanBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSanBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(selectLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(searchSanBay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectLuaChon)
                    .addComponent(searchSanBay))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemSanBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemSanBayActionPerformed
        // TODO add your handling code here:
        themSanBay();
    }//GEN-LAST:event_jButtonThemSanBayActionPerformed

    private void jButtonSuaSanBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaSanBayActionPerformed
        // TODO add your handling code here:
        suaSanBay();
    }//GEN-LAST:event_jButtonSuaSanBayActionPerformed

    private void jButtonXoaSanBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaSanBayActionPerformed
        // TODO add your handling code here:
        xoaSanBay();
    }//GEN-LAST:event_jButtonXoaSanBayActionPerformed

    private void tableSanBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanBayMouseClicked
        // TODO add your handling code here:
        clickTableRowSB();
    }//GEN-LAST:event_tableSanBayMouseClicked

    private void searchSanBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSanBayActionPerformed
        // TODO add your handling code here:
        timKiemSanBay();
    }//GEN-LAST:event_searchSanBayActionPerformed

    public void themSanBay() {
        String tenSB = txtTenSB.getText();
        String diaChi = txtDiaChi.getText();

        SanBayDTO sb = new SanBayDTO();
        sb.setTenSanBay(tenSB);
        sb.setDiaChi(diaChi);

        sanbayBUS.themSanBay(sb);
    }

    public void suaSanBay() {
        String maSB = txtMaSB.getText();
        String tenSB = txtTenSB.getText();
        String diaChi = txtDiaChi.getText();

        SanBayDTO sb = new SanBayDTO(maSB, tenSB, diaChi);

        sanbayBUS.suaSanBay(sb);
    }

    public void xoaSanBay() {
        String maSB = txtMaSB.getText();
        sanbayBUS.xoaSanBay(maSB);
    }

    public void getListSanBay() {
        dtmSanBay.setRowCount(0);
        dssb = sanbayBUS.getListSanBay();

        for (SanBayDTO sb : dssb) {
            Vector vec = new Vector();
            vec.add(sb.getMaSanBay());
            vec.add(sb.getTenSanBay());
            vec.add(sb.getDiaChi());

            dtmSanBay.addRow(vec);
        }
        tableSanBay.setModel(dtmSanBay);
    }

    public void clickTableRowSB() {
        int row = tableSanBay.getSelectedRow();
        if (row > -1) {
            txtMaSB.setText(tableSanBay.getValueAt(row, 0) + "");
            txtTenSB.setText(tableSanBay.getValueAt(row, 1) + "");
            txtDiaChi.setText(tableSanBay.getValueAt(row, 2) + "");
        }
    }

    public void timKiemSanBay() {
        String tuKhoa = txtTuKhoa.getText();
        String luaChon = selectLuaChon.getSelectedItem().toString();

        if (luaChon == "Mã sân bay") {
            dssb = sanbayBUS.timKiemSanBayTheoMa(tuKhoa);
        }

        if (luaChon == "Tên sân bay") {
            dssb = sanbayBUS.timKiemSanBayTheoTên(tuKhoa);
        }

        if (luaChon == "Địa chỉ") {
            dssb = sanbayBUS.timKiemSanBayTheoDiaChi(tuKhoa);
        }

        for (SanBayDTO sb : dssb) {
            Vector vec = new Vector();
            vec.add(sb.getMaSanBay());
            vec.add(sb.getTenSanBay());
            vec.add(sb.getDiaChi());

            dtmSanBay.addRow(vec);
        }
        tableSanBay.setModel(dtmSanBay);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSuaSanBay;
    private javax.swing.JButton jButtonThemSanBay;
    private javax.swing.JButton jButtonXoaSanBay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton searchSanBay;
    private javax.swing.JComboBox<String> selectLuaChon;
    private javax.swing.JTable tableSanBay;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaSB;
    private javax.swing.JTextField txtTenSB;
    private javax.swing.JTextField txtTuKhoa;
    // End of variables declaration//GEN-END:variables
}
