/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QuanLyBanVeMayBay.GUI.form;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

import QuanLyBanVeMayBay.BUS.MayBayBUS;
import QuanLyBanVeMayBay.DTO.MayBay;
import QuanLyBanVeMayBay.BUS.HangBayBUS;
import QuanLyBanVeMayBay.DTO.HangBayDTO;

/**
 *
 * @author Dell
 */
public class MayBayGUI extends javax.swing.JPanel {

    /**
     * Creates new form MayBayGUI
     */
    private DefaultTableModel dtmMayBay = new DefaultTableModel();
    MayBayBUS maybayBUS = new MayBayBUS();
    ArrayList<MayBay> dsmb = new ArrayList<>();
    HangBayBUS hangbayBUS = new HangBayBUS();
    ArrayList<HangBayDTO> dshb = new ArrayList<>();

    public MayBayGUI() {
        initComponents(); 
//        getListMayBay();
//        getListHangBay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        txtMaMB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTenMB = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtSoLuongGhe = new javax.swing.JTextField();
        jButtonThemMayBay = new javax.swing.JButton();
        jButtonSuaMayBay = new javax.swing.JButton();
        jButtonXoaMayBay = new javax.swing.JButton();
        txtMaHang = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        txtTuKhoa = new javax.swing.JTextField();
        selectLuaChon = new javax.swing.JComboBox<>();
        seachMayBay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMayBay = new javax.swing.JTable();

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Mã máy bay");

        txtMaMB.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tên Máy Bay");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setText("Tên Hãng");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("Số Lượng Ghế");

        jButtonThemMayBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonThemMayBay.setText("Thêm");
        jButtonThemMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemMayBayActionPerformed(evt);
            }
        });

        jButtonSuaMayBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSuaMayBay.setText("Sửa");
        jButtonSuaMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaMayBayActionPerformed(evt);
            }
        });

        jButtonXoaMayBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonXoaMayBay.setText("Xóa");
        jButtonXoaMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaMayBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButtonThemMayBay)
                        .addGap(65, 65, 65)
                        .addComponent(jButtonSuaMayBay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jButtonXoaMayBay))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel40))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaMB)
                                    .addComponent(txtTenMB)
                                    .addComponent(txtSoLuongGhe)
                                    .addComponent(txtMaHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaMB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtTenMB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel39)
                    .addComponent(txtSoLuongGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThemMayBay)
                    .addComponent(jButtonSuaMayBay)
                    .addComponent(jButtonXoaMayBay))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        txtTuKhoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTuKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuKhoaActionPerformed(evt);
            }
        });

        selectLuaChon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectLuaChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã máy bay", "Tên máy bay", "Mã hãng bay" }));

        seachMayBay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seachMayBay.setText("Tìm kiếm");
        seachMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seachMayBayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Quản Lý Máy Bay");

        tableMayBay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Máy Bay", "Tên Máy Bay", "Mã Hãng", "Số Lượng Ghế"
            }
        ));
        tableMayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMayBayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMayBay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(selectLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(seachMayBay))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seachMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemMayBayActionPerformed
        // TODO add your handling code here:
        themMayBay();
    }//GEN-LAST:event_jButtonThemMayBayActionPerformed

    private void jButtonSuaMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaMayBayActionPerformed
        // TODO add your handling code here:
        suaMayBay();
    }//GEN-LAST:event_jButtonSuaMayBayActionPerformed

    private void jButtonXoaMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaMayBayActionPerformed
        // TODO add your handling code here:
        xoaMayBay();
    }//GEN-LAST:event_jButtonXoaMayBayActionPerformed

    private void txtTuKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuKhoaActionPerformed

    private void seachMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seachMayBayActionPerformed
        // TODO add your handling code here:
        timKiemMayBay();
    }//GEN-LAST:event_seachMayBayActionPerformed

    private void tableMayBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMayBayMouseClicked
        // TODO add your handling code here:
        clickTableRowMB();
    }//GEN-LAST:event_tableMayBayMouseClicked

    public void getListHangBay(){
        dshb = hangbayBUS.getListHangBay();
        for(HangBayDTO hb : dshb){
            txtMaHang.addItem(hb.getTenHang());
        }
    }
    
    public void themMayBay() {
        String tenMB = txtTenMB.getText();
        //int maHB = Integer.parseInt(txtMaHB.getText());
        int maHB = hangbayBUS.getIDHangBay(txtMaHang.getSelectedItem().toString());
        int soLuongGhe = Integer.parseInt(txtSoLuongGhe.getText());
        MayBay mb = new MayBay();
        mb.setTenMayBay(tenMB);
        mb.setMaHang(maHB);
        mb.setSoLuongGhe(soLuongGhe);

        maybayBUS.themMayBay(mb);
        listMayBay();
    }

    public void suaMayBay() {
        int maMB = Integer.parseInt(txtMaMB.getText());
        String tenMB = txtTenMB.getText();
        //int maHB = Integer.parseInt(txtMaHB.getText());
        int maHB = hangbayBUS.getIDHangBay(txtMaHang.getSelectedItem().toString());
        int soLuongGhe = Integer.parseInt(txtSoLuongGhe.getText());
        
        
        MayBay mb = new MayBay();
        mb.setTenMayBay(tenMB);
        mb.setMaHang(maHB);
        mb.setSoLuongGhe(soLuongGhe); 
        mb.setMaMayBay(maMB);

        maybayBUS.suaMayBay(mb);
        listMayBay();
    }

    public void xoaMayBay() {
        int maMB = Integer.parseInt(txtMaMB.getText());
        int i = tableMayBay.getSelectedRow();
        
        if(maybayBUS.xoaMayBay(maMB)){
            dtmMayBay.removeRow(i);
            tableMayBay.setModel(dtmMayBay);
            txtMaMB.setText("");
            txtTenMB.setText("");
            //txtMaHB.setText("");
            txtSoLuongGhe.setText("");
        }
    }

    public void getListMayBay() {
        dtmMayBay.setRowCount(0);
        dsmb = maybayBUS.getListMayBay();

        Vector<Object> header = new Vector<>();
        header.add("Mã Máy Bay");
        header.add("Tên Máy Bay");
        header.add("Hãng Bay");
        header.add("Số Lượng Ghế");

        if (dtmMayBay.getRowCount() == 0) {
            dtmMayBay = new DefaultTableModel(header, 0);
        }

        for (MayBay mb : dsmb) {
            Vector<Object> vec = new Vector<>();
            vec.add(mb.getMaMayBay());
            vec.add(mb.getTenMayBay());
            vec.add(mb.getMaHang());
            vec.add(mb.getSoLuongGhe());

            dtmMayBay.addRow(vec);
        }
        tableMayBay.setModel(dtmMayBay);
    }

    public void clickTableRowMB() {
        int row = tableMayBay.getSelectedRow();
        String tenHangBay = getTen(tableMayBay.getValueAt(row, 2).toString());
        if (row > -1) {
            txtMaMB.setText(tableMayBay.getValueAt(row, 0) + "");
            txtTenMB.setText(tableMayBay.getValueAt(row, 1) + "");
            //txtMaHB.setText(tableMayBay.getValueAt(row, 2) + "");
            txtMaHang.setSelectedItem(tenHangBay);
            txtSoLuongGhe.setText(tableMayBay.getValueAt(row, 3) + "");
        }
    }

    public void timKiemMayBay() {
        String tuKhoa = txtTuKhoa.getText();
        String luaChon = selectLuaChon.getSelectedItem().toString();

        if(luaChon == "Tất Cả"){
            dsmb = maybayBUS.listMayBay();
        }
        
        if (luaChon == "Mã máy bay") {
            dsmb = maybayBUS.timKiemMayBayTheoMa(tuKhoa);
        }

        if (luaChon == "Tên máy bay") {
            dsmb = maybayBUS.timKiemMayBayTheoTen(tuKhoa);
        }

        if (luaChon == "Mã hãng bay") {
            dsmb = maybayBUS.timKiemMayBayTheoHang(tuKhoa);
        }
            
            dtmMayBay.setRowCount(0);
        
            Vector<Object> header = new Vector<>();
            header.add("Mã máy bay");
            header.add("Tên máy bay");
            header.add("Mã hãng bay");
            header.add("Số lượng ghế");

            if (dtmMayBay.getRowCount() == 0) {
                dtmMayBay = new DefaultTableModel(header, 0);
            }

            for (MayBay mb : dsmb) {
                Vector<Object> vec = new Vector<>();
                vec.add(mb.getMaMayBay());
                vec.add(mb.getTenMayBay());
                vec.add(mb.getMaHang());
                vec.add(mb.getSoLuongGhe());

                dtmMayBay.addRow(vec);
            }
            tableMayBay.setModel(dtmMayBay);
    }
    
    public void listMayBay(){
        try {
            dtmMayBay.setRowCount(0);
            dsmb = maybayBUS.listMayBay();
            System.out.print("Hello");
            Vector<Object> header = new Vector<>();
            header.add("Mã máy bay");
            header.add("Tên máy bay");
            header.add("Mã hãng bay");
            header.add("Số lượng ghế");

            if (dtmMayBay.getRowCount() == 0) {
                dtmMayBay = new DefaultTableModel(header, 0);
            }

            for (MayBay mb : dsmb) {
                Vector<Object> vec = new Vector<>();
                vec.add(mb.getMaMayBay());
                vec.add(mb.getTenMayBay());
                vec.add(mb.getMaHang());
                vec.add(mb.getSoLuongGhe());

                dtmMayBay.addRow(vec);
            }
            tableMayBay.setModel(dtmMayBay);
        } catch (Exception e) {

        }
    }
    
    public String getTen(String ma){
        String n = "";
        for(HangBayDTO hb : dshb){
            if(Integer.parseInt(ma) == hb.getMaHang()){
                n = hb.getTenHang();
                return n;
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSuaMayBay;
    private javax.swing.JButton jButtonThemMayBay;
    private javax.swing.JButton jButtonXoaMayBay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton seachMayBay;
    private javax.swing.JComboBox<String> selectLuaChon;
    private javax.swing.JTable tableMayBay;
    private javax.swing.JComboBox<String> txtMaHang;
    private javax.swing.JTextField txtMaMB;
    private javax.swing.JTextField txtSoLuongGhe;
    private javax.swing.JTextField txtTenMB;
    private javax.swing.JTextField txtTuKhoa;
    // End of variables declaration//GEN-END:variables
}
