/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QuanLyBanVeMayBay.GUI.form;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

import QuanLyBanVeMayBay.GUI.form.TuyenBayGUI;
import QuanLyBanVeMayBay.BUS.TuyenBayBUS;
import QuanLyBanVeMayBay.DTO.TuyenBayDTO;

/**
 *
 * @author Dell
 */
public class TuyenBayGUI extends javax.swing.JPanel {

    /**
     * Creates new form TuyenBayGUI
     */
    DefaultTableModel dtmTuyenBay = new DefaultTableModel();
    TuyenBayBUS tuyenbayBUS = new TuyenBayBUS();
    ArrayList<TuyenBayDTO> dstb = new ArrayList<>();

    public TuyenBayGUI() {
        initComponents();
        getListTuyenBay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaTB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSBcatCanh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSBhaCanh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGioCatCanh = new javax.swing.JTextField();
        jButtonThemTuyenBay = new javax.swing.JButton();
        jButtonSuaTuyenBay = new javax.swing.JButton();
        jButtonXoaTuyenBay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtGioHaCanh = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTuyenBay = new javax.swing.JTable();
        txtTuKhoa = new javax.swing.JTextField();
        searchTuyenBay = new javax.swing.JButton();
        selectLuaChon = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã Tuyến Bay");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Sân Bay Cất Cánh");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Sân Bay Hạ Cánh");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Giờ Cất Cánh");

        txtGioCatCanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioCatCanhActionPerformed(evt);
            }
        });

        jButtonThemTuyenBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonThemTuyenBay.setText("Thêm");
        jButtonThemTuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemTuyenBayActionPerformed(evt);
            }
        });

        jButtonSuaTuyenBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSuaTuyenBay.setText("Sửa");
        jButtonSuaTuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaTuyenBayActionPerformed(evt);
            }
        });

        jButtonXoaTuyenBay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonXoaTuyenBay.setText("Xóa");
        jButtonXoaTuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaTuyenBayActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Giờ Hạ Cánh");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(48, 48, 48)
                            .addComponent(txtMaTB, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jButtonThemTuyenBay)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jButtonSuaTuyenBay)
                                    .addGap(77, 77, 77)
                                    .addComponent(jButtonXoaTuyenBay))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSBcatCanh)
                                        .addComponent(txtSBhaCanh)
                                        .addComponent(txtGioCatCanh)
                                        .addComponent(txtGioHaCanh)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaTB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSBcatCanh))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSBhaCanh))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGioCatCanh))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtGioHaCanh, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThemTuyenBay)
                    .addComponent(jButtonSuaTuyenBay)
                    .addComponent(jButtonXoaTuyenBay))
                .addGap(27, 27, 27))
        );

        tableTuyenBay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Tuyến Bay", "Mã Sân Bay Cất Cánh", "Mã Sân Bay Hạ Cánh", "Giờ Cất Cánh", "Giờ Hạ Cánh"
            }
        ));
        tableTuyenBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTuyenBayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableTuyenBay);

        txtTuKhoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        searchTuyenBay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchTuyenBay.setText("Tìm kiếm");
        searchTuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTuyenBayActionPerformed(evt);
            }
        });

        selectLuaChon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectLuaChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả", "Mã Tuyến Bay", "Sân Bay Cất Cánh", "Sân Bay Hạ Cánh" }));
        selectLuaChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectLuaChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(searchTuyenBay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Quản Lý Tuyến Bay");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGioCatCanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioCatCanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioCatCanhActionPerformed

    private void jButtonSuaTuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaTuyenBayActionPerformed
        // TODO add your handling code here:
        suaTuyenBay();
    }//GEN-LAST:event_jButtonSuaTuyenBayActionPerformed

    private void jButtonThemTuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemTuyenBayActionPerformed
        // TODO add your handling code here:
        themTuyenBay();
    }//GEN-LAST:event_jButtonThemTuyenBayActionPerformed

    private void jButtonXoaTuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaTuyenBayActionPerformed
        // TODO add your handling code here:
        xoaTuyenBay();
    }//GEN-LAST:event_jButtonXoaTuyenBayActionPerformed

    private void tableTuyenBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTuyenBayMouseClicked
        // TODO add your handling code here:
        clickTableRowTB();
    }//GEN-LAST:event_tableTuyenBayMouseClicked

    private void selectLuaChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectLuaChonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectLuaChonActionPerformed

    private void searchTuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTuyenBayActionPerformed
        // TODO add your handling code here:
        timKiemTuyenBay();
    }//GEN-LAST:event_searchTuyenBayActionPerformed

    public void themTuyenBay() {
        int sanBayCatCanh = Integer.parseInt(txtSBcatCanh.getText());
        int sanBayHaCanh = Integer.parseInt(txtSBhaCanh.getText());
        String gioCatCanh = txtGioCatCanh.getText();
        String gioHaCanh = txtGioHaCanh.getText();

        TuyenBayDTO tb = new TuyenBayDTO();
        tb.setSanBayCatCanh(sanBayCatCanh);
        tb.setSanBayHaCanh(sanBayHaCanh);
        tb.setGioCatCanh(gioCatCanh);
        tb.setGioHaCanh(gioHaCanh);

        tuyenbayBUS.themTuyenBay(tb);
        
        showListTuyenBay();
    }

    public void suaTuyenBay() {
        int maTuyenBay = Integer.parseInt(txtMaTB.getText());
        int sanBayCatCanh = Integer.parseInt(txtSBcatCanh.getText());
        int sanBayHaCanh = Integer.parseInt(txtSBhaCanh.getText());
        String gioCatCanh = txtGioCatCanh.getText();
        String gioHaCanh = txtGioHaCanh.getText();

        TuyenBayDTO tb = new TuyenBayDTO(maTuyenBay, sanBayCatCanh, sanBayHaCanh, gioCatCanh, gioHaCanh);

        tuyenbayBUS.suaTuyenBay(tb);
        
        showListTuyenBay();
    }

    public void xoaTuyenBay() {
        int maTuyenBay = Integer.parseInt(txtMaTB.getText());
        int i = tableTuyenBay.getSelectedRow();
        if(tuyenbayBUS.xoaTuyenBay(maTuyenBay)){
            dtmTuyenBay.removeRow(i);
            tableTuyenBay.setModel(dtmTuyenBay);
            
            txtMaTB.setText("");
            txtSBcatCanh.setText("");
            txtSBhaCanh.setText("");
            txtSBhaCanh.setText("");
            txtGioCatCanh.setText("");
            txtGioHaCanh.setText("");
        }
    }

    public void getListTuyenBay() {
        dtmTuyenBay.setRowCount(0);
        dstb = tuyenbayBUS.getListTuyenBay();

        Vector<Object> header = new Vector<>();
        header.add("Mã Tuyến Bay");
        header.add("Mã Sân Bay Cất Cánh");
        header.add("Mã Sân Bay Hạ Cánh");
        header.add("Giờ Cất Cánh");
        header.add("Giờ Hạ Cánh");

        if (dtmTuyenBay.getRowCount() == 0) {
            dtmTuyenBay = new DefaultTableModel(header, 0);
        }

        for (TuyenBayDTO tb : dstb) {
            Vector<Object> vec = new Vector<>();
            vec.add(tb.getMaTuyenBay());
            vec.add(tb.getSanBayCatCanh());
            vec.add(tb.getSanBayHaCanh());
            vec.add(tb.getGioCatCanh());
            vec.add(tb.getGioHaCanh());

            dtmTuyenBay.addRow(vec);
        }
        tableTuyenBay.setModel(dtmTuyenBay);
    }
    
    public void showListTuyenBay(){
        dtmTuyenBay.setRowCount(0);
        dstb = tuyenbayBUS.showListTuyenBay();

        Vector<Object> header = new Vector<>();
        header.add("Mã Tuyến Bay");
        header.add("Mã Sân Bay Cất Cánh");
        header.add("Mã Sân Bay Hạ Cánh");
        header.add("Giờ Cất Cánh");
        header.add("Giờ Hạ Cánh");

        if (dtmTuyenBay.getRowCount() == 0) {
            dtmTuyenBay = new DefaultTableModel(header, 0);
        }

        for (TuyenBayDTO tb : dstb) {
            Vector<Object> vec = new Vector<>();
            vec.add(tb.getMaTuyenBay());
            vec.add(tb.getSanBayCatCanh());
            vec.add(tb.getSanBayHaCanh());
            vec.add(tb.getGioCatCanh());
            vec.add(tb.getGioHaCanh());

            dtmTuyenBay.addRow(vec);
        }
        tableTuyenBay.setModel(dtmTuyenBay);
    }

    public void clickTableRowTB() {
        int row = tableTuyenBay.getSelectedRow();
        if (row > -1) {
            txtMaTB.setText(tableTuyenBay.getValueAt(row, 0) + "");
            txtSBcatCanh.setText(tableTuyenBay.getValueAt(row, 1) + "");
            txtSBhaCanh.setText(tableTuyenBay.getValueAt(row, 2) + "");
            txtGioCatCanh.setText(tableTuyenBay.getValueAt(row, 3) + "");
            txtGioHaCanh.setText(tableTuyenBay.getValueAt(row, 4) + "");
        }
    }

    public void timKiemTuyenBay() {
        String tuKhoa = txtTuKhoa.getText();
        String luaChon = selectLuaChon.getSelectedItem().toString();

        if(luaChon == "Tất Cả"){
            dstb = tuyenbayBUS.showListTuyenBay();
        }
        
        if (luaChon == "Mã Tuyến Bay") {
            dstb = tuyenbayBUS.timKiemTuyenBayTheoMa(tuKhoa);
        }

        if (luaChon == "Sân Bay Cất Cánh") {
            dstb = tuyenbayBUS.timKiemTuyenBayTheoSBCatCanh(tuKhoa);
        }

        if (luaChon == "Sân Bay Hạ Cánh") {
            dstb = tuyenbayBUS.timKiemTuyenBayTheoSBHaCanh(tuKhoa);
        }
        
        dtmTuyenBay.setRowCount(0);

        Vector<Object> header = new Vector<>();
        header.add("Mã Tuyến Bay");
        header.add("Mã Sân Bay Cất Cánh");
        header.add("Mã Sân Bay Hạ Cánh");
        header.add("Giờ Cất Cánh");
        header.add("Giờ Hạ Cánh");

        if (dtmTuyenBay.getRowCount() == 0) {
            dtmTuyenBay = new DefaultTableModel(header, 0);
        }

        for (TuyenBayDTO tb : dstb) {
            Vector<Object> vec = new Vector<>();
            vec.add(tb.getMaTuyenBay());
            vec.add(tb.getSanBayCatCanh());
            vec.add(tb.getSanBayHaCanh());
            vec.add(tb.getGioCatCanh());
            vec.add(tb.getGioHaCanh());

            dtmTuyenBay.addRow(vec);
        }
        tableTuyenBay.setModel(dtmTuyenBay);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSuaTuyenBay;
    private javax.swing.JButton jButtonThemTuyenBay;
    private javax.swing.JButton jButtonXoaTuyenBay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchTuyenBay;
    private javax.swing.JComboBox<String> selectLuaChon;
    private javax.swing.JTable tableTuyenBay;
    private javax.swing.JTextField txtGioCatCanh;
    private javax.swing.JTextField txtGioHaCanh;
    private javax.swing.JTextField txtMaTB;
    private javax.swing.JTextField txtSBcatCanh;
    private javax.swing.JTextField txtSBhaCanh;
    private javax.swing.JTextField txtTuKhoa;
    // End of variables declaration//GEN-END:variables
}
